apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: markettool-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: telegram-static-ip
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "route"
    nginx.ingress.kubernetes.io/session-cookie-expires: "3600"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "3600"
spec:
  tls:
  - hosts:
    - 34.8.35.67
    secretName: tls-secret
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: markettool-service
            port:
              number: 8080
